export const GET_TRANSACTION_DATA = 'GET_TRANSACTION_DATA'
export const GET_FILTERED_DATA = 'GET_FILTERED_DATA'
export const CLEAR_FILTERED_DATA = 'CLEAR_FILTERED_DATA';
export const ADD_TRANSACTION_TO_SHIFT = 'ADD_TRANSACTION_TO_SHIFT';
export const ADD_EVENT_TO_SHIFT= 'ADD_EVENT_TO_SHIFT';




